const auth = require('../auth')
const express = require('express')
const Top5ListController = require('../controllers/top5list-controller')
const UserController = require('../controllers/user-controller')
const router = express.Router()

router.post('/top5list', auth.verify, Top5ListController.createTop5List)
router.put('/top5list/:id/:user', auth.verify, Top5ListController.userUpdateTop5List)
router.put('/top5list/:id', auth.verify, Top5ListController.updateTop5List)
router.delete('/top5list/:id/:user', auth.verify, Top5ListController.deleteTop5List)
router.get('/top5list/:id', auth.verify, Top5ListController.getTop5ListById)
router.get('/top5lists', auth.verify, Top5ListController.getTop5Lists)
router.get('/usertop5lists', auth.verify, Top5ListController.getUserTop5Lists)
router.put('/publishtop5list/:id/:user', auth.verify, Top5ListController.publishTop5List)
router.get('/gencommunitylists', auth.verify, Top5ListController.generateCommunityLists)

router.post('/register', UserController.registerUser)
router.get('/loggedIn', UserController.getLoggedIn)
router.get('/login/', UserController.loginUser)
router.get('/logout/', UserController.logoutUser)
router.get('/loginguest/', UserController.loginGuest)
module.exports = router